// <auto-generated />
using System;
using AddBudget.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddBudget.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180827083205_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AddBudget.API.Models.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ActiveFlag");

                    b.Property<DateTime>("ActualDeadline");

                    b.Property<string>("ArabicDescrption");

                    b.Property<string>("ArabicName");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("DeleteDate");

                    b.Property<bool>("DeleteFlag");

                    b.Property<DateTime>("DeleteTime");

                    b.Property<string>("DeleteUser");

                    b.Property<string>("EnglishDescrption");

                    b.Property<string>("EnglishName");

                    b.Property<DateTime>("EntryDate");

                    b.Property<DateTime>("EntryTime");

                    b.Property<string>("EntryUser");

                    b.Property<DateTime>("EstimatedDeadline");

                    b.Property<DateTime>("LastModificationDate");

                    b.Property<DateTime>("LastModificationTime");

                    b.Property<string>("LastModificationUser");

                    b.Property<int>("NumberOfBranchesAlreadyPerformed");

                    b.Property<int>("NumberOfBranchesUnderConstruction");

                    b.Property<int>("NumberOfForecastedBranches");

                    b.HasKey("BudgetId");

                    b.ToTable("Budgets");
                });
#pragma warning restore 612, 618
        }
    }
}
